name: CI

on: workflow _dispatch

Jobs:

build:

runs-on: windows-latest timeout-minutes: 9999

steps:

- name: Download Ngrok & NSSM

run: |

Invoke-WebRequest https://raw.githubusercontent.com/charan2004152004/Ngrok-Exe/main/ngrok.exe -OutFile ngrok.exe Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Projecti/main/Files/nssm.exe -OutFile nesm.exe

- name: Copy NSSM & Ngrok to Windows Directory.

copy nesm.exe C:\Windows\System32

copy ngrok.exe C:\Windows\System32 - name: Connect your NGROK account

run: Angrok.exe authtoken SEnv:NGROK_AUTH_TOKEN

env:

NGROK_AUTH_TOKEN: $ secrets.NGROK_AUTH_TOKEN }}

- name: Download Important Files.

run:

Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Projecti/main/Files/NGROK-US.bat -OutFile NGROR-US.bat Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Project1/main/Files/NGROK-CHECK.bat -Out File NGROR-CHECK.bat

Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Test Project1/main/Files/loop.bat -OutFile loop.bat

- name: Make YML file for NGROK. run: start NGROK-US.bat

-name: Enable RDP Access.

run:

Set-ItemProperty -Path HKLM\System\CurrentControlSet\Control\Terminal Server-name "DenyTSConnections" -Value 0 Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations RDF-Top' -name "UserAuthentication" -Value 1

- name: Create Tunnel

run: sc start ngrok

- name: Connect to your RDP 2core-7GB Ram.

run: cmd /e NGROK-CHECK.bat

name: All Done! You can close Tab now! Maximum VM time:6h.

run: cmd /e loop.bat
